### ISSUE TITLE
Upgrade elasticsearch, filebeat, logstash and kibana containers to release 7.11.2

### ISSUE THREAD

**Issue by ManofWax** [certego/PcapMonkey#11]
Upgrades the following containers to latest release (7.11):

- [ ] elasticsearch
- [ ] logstash
- [ ] kibana
- [ ] filebeat

**Comment by hariomch** [comment]
#12  Upgraded the following containers:
- [x] Elasticsearch
- [X] Logstash
- [X] Kibana
- [X] Filebeat
