### ISSUE TITLE
Upgrade Elasticsearch, Logstash and Filebeat to release 7.13.x

### ISSUE THREAD

**Issue by ManofWax** [certego/PcapMonkey#20]
Upgrade Elasticsearch, Logstash and Filebeat to latest releases.

The following things should be checked:

- [ ] Importing `kibana.ndjson`  and see if it still compatbile for lastest kibana
- [ ] Runnig pcaps and see if the log data are being imported correctly

**Comment by gokuljs** [comment]
![image](https://user-images.githubusercontent.com/51263906/122365571-65731c80-cf78-11eb-8f53-2ccfb8e02dc8.png)

**Comment by ManofWax** [comment]
@gokuljs what is this about? Have you got some issues related on elastic upgrade?

**Comment by gokuljs** [comment]
![image](https://user-images.githubusercontent.com/51263906/122550786-bc005980-d051-11eb-9789-d51dffa73ffb.png)
This happened after the upgrade

**Comment by hariomch** [comment]
@gokuljs can you elaborate on the problem you are facing, and what steps you took.

**Comment by gokuljs** [comment]
ya, I Just clone your repo did all the procedures mentioned in your readme.MD file and ran  2020-12-03-traffic-analysis-quiz.pcap, now when I opened the kibana dashboard after setting up index patterns I filtered tags to zeek there is no data displayed there . Even I tried expanding the time range also

**Comment by gokuljs** [comment]
And when i was running docker-compose Zeek suricata this is the error that showed in the command line 
![image](https://user-images.githubusercontent.com/51263906/123322283-bcb55600-d551-11eb-96f9-8d4284ac3928.png)

**Comment by hariomch** [comment]
Can you tell what exactly are the changes you made in order to upgrade the ELK. Its working fine in my machine and I am not able to reproduce the issue.

**Comment by gokuljs** [comment]
I did not make any changes . What I have done I just cloned this repo and ran those commands in readme and it started downloading and I started it

**Comment by gokuljs** [comment]
I think elk is working fine see at that pick zeek1 its showing some sort of fatal error right

**Comment by ManofWax** [comment]
@gokuljs Are you using docker on windows with WSL?

**Comment by gokuljs** [comment]
Yes I am using docker on windows with wsl2

**Comment by ManofWax** [comment]
Ok, thanks I just got the same problem reported by another user with windows in WSL2. Unluckly I don't have a Windows machine to test it out.

From the logs It seems thet zeek container does not have permissions to write on `/logs/zeek` but I don't know why is  it happening on windows.

Maybe It could be somewhat releated to this: https://github.com/docker/for-win/issues/4824

**Comment by ManofWax** [comment]
@hariomch I've some issues on filebeat: I've just commited f1995b8 because filebeat path was wrong. I don't know how it was working for you.

When importing zeek logs it seems it tries to import `loaded_scripts.log` (that i think it useless and I'd like not to import it) as `zeek.x509` and obiouvsly the parser fails:

![image](https://user-images.githubusercontent.com/188858/123831250-6d31aa00-d904-11eb-9e11-f8330726c472.png)

Is it something it happens to you?

**Comment by hariomch** [comment]
Hm.. I didn't encounter this problem, not sure why is it so.

**Comment by gokuljs** [comment]
Even I was trying to analyze some packets related to application-layer threats. so In the old version after running the packet the contents related to Suricata was not shown in the kibana dashboard . after setting tags to suricata and setting up the time limit also the data was completely empty .

**Comment by gokuljs** [comment]
This is completely a different doubt. now if I have an old version of the docker image of elk stack and Suricata and Zeek is there. any way to directly upgrade it or should we clone the repo again and run it?

**Comment by ManofWax** [comment]
Hi, the new version: the one hariomch is working with is on developer branch.
So you can pull the developer branch and follow the new guide Hariom has written here: https://github.com/certego/PcapMonkey/wiki/2.-Analyzing-files (remember that is a work in progress but it's already quite complete).

You don't need to delete anything, if you import the new `filebeat.ndjson` you should see the new data on `filebeat*` index pattern.

**Comment by ManofWax** [comment]
Implemented
