### ISSUE TITLE
Improve winevent log ingestion

### ISSUE THREAD

**Issue by ManofWax** [certego/PcapMonkey#3]
Right now we are using a python script to load in elasticsearch winevent log data. It should be great to use directly winlogbeat if possible

**Comment by ManofWax** [comment]
Elasticsearch uses [https://www.elastic.co/beats/winlogbeat](winlogbeat) to collect and process windows event logs. Winlogbeat can read `.evtx` files but, at the time of writing, winlogbeat only works on windows machines.

Right now pcapmonkey uses this code `https://github.com/certego/evtxtoelk` to read `.evtx` files and saving them directly in elasticsearch.

The goal of this task is saving `.evtx` logs using the same data schema of winlogbeat: https://www.elastic.co/guide/en/beats/winlogbeat/current/exported-fields.html in this way we can leverege other elasticsearch functionalities (like [SIEM](https://www.elastic.co/siem)) and have the data in the correct format.

To achive this task we could:

- Improve `evtxtoelk` code by renaming the fields with the names describet on winlogbeat exported fields
- Replace `evtxtoelk` with winlogbeat but we need to make it run on linux

I don't know if it is possible to run winlogbeat on linux, I quickly read the code and it seemes it uses Windows APIs. I believe improving `evtxtolek` code is the correct way

**Comment by hariomch** [comment]
Here's a collection of  `.evtx` file samples, which may help in testing winlogbeat: [https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES](https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES)
