### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tklengyel** [certego/PcapMonkey#7]
Could you please add a LICENSE file explaining what open-source license this repository is under? Thanks

**Comment by ManofWax** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improvment elastic_query](https://trello.com/c/RLjIorok/79-improvment-elasticquery)

**Comment by ManofWax** [comment]
Hello, I just added a license.txt file. The PcapMonkey is under the GPLv3 license but the software it uses (elasticsearch stack, zeek, suricata, etc.) are under their licenses
